### ISSUE TITLE
Can't find ami-141bb974

### ISSUE THREAD

**Issue by fEDUntu** [antisnatchor/phishlulz#2]
Hi there, 
i'm trying to find your dedicated Image Template for PhishLulz called ami-141bb974 but I can't find on the Amazon MarketPlace (the message says "No AMI's found matching your filter criteria") 
Any suggestions?
Thanks in advance.

Fede.

**Comment by antisnatchor** [comment]
You must be in the US West (Oregon) EC2 region to see the public AMI:

![screen shot 2016-12-12 at 09 41 04](https://cloud.githubusercontent.com/assets/910293/21092884/3cb08ba8-c04f-11e6-872f-fc12a33a819d.png)

**Comment by p0wner** [comment]
Hello,

Could you please confirm if the public AMI 141bb974 is still available? I am currently searching through the US West Oregon EC2, but not seeing the image.

I appreciate your help.
