### ISSUE TITLE
Is this ethical?

### ISSUE THREAD

**Issue by andrew-carroll** [antisnatchor/phishlulz#3]
I came across this repository while looking for freelance gigs; someone was offering $25 for a developer to set it up on an Amazon instance. Am I correct in understanding that this tool's explicit purpose is facilitating illegal phishing campaigns?

**Comment by wlbreen** [comment]
Andrew  -  Yes, this type of software assists penetration\Social Engineering test.  Valid uses are when a company asks for, and wants to test the ability of their users to see through phishing attempts.  Yes it can be used in an illegal manner, but in this case the client wants the test to happen.

**Comment by antisnatchor** [comment]
LOL at that 25$ price :-)
